@startuml menu
skinparam classBackgroundColor AliceBlue
skinparam classBorderColor Blue
skinparam classFontName Comic Sans 
skinparam classFontSize 20

class Empleado {
 - _id: string
 - nombre_usuario: String
 - nombre: String
 - apellido: String
 - numero_teléfono: String
 - correo: String
 - contraseña: String
}

class ProductosMenu {
  - _id: string
  - categoría: Categoría
  - nombre: String
  - descripción: String
}

class Variación {
  - _id: string
  - tamaño: Tamaño
  - precio: double
  - producto_id: string
}

class Pedido {
 - _id: string
 - numero_pedido: int
 - precio_total: double
}

class DetallePedido {
 - _id: string
 - cantidad: int
 - pedido_id: string
 - producto_id: string
}

enum Tamaño {
  Regular
  Grande
  Unico
}

enum Categoría {
  Plato
  Bebida
}

ProductosMenu "1" *-- "1..*" Variación 
Pedido "1" *-- "1..*" DetallePedido 

ProductosMenu "1" -- "0..*" DetallePedido 

@enduml
