@startuml menu 
skinparam classBackgroundColor AliceBlue
skinparam classBorderColor Blue
skinparam classFontName Comic Sans 
skinparam classFontSize 20

class Dish {
  - _id: int
  - category: String
  - dish_name: String
  - description: String
}

class DishVariation {
  - _id: int
  - variation: String
  - price: double
}

class Ticket {
  - _id: int
  - orderNumber: int
  - dishes: List<DishDetail>
  - totalAmount: double
}

class DishDetail {
  - _id: int
  - dishName: String
  - size: String
  - price: double
  - numberOfDishes: int 
}

Dish "1" --o "1..*" DishVariation : contains
Ticket "1" --o "1..*" DishDetail : contains

@enduml
