@startuml menu
skinparam classBackgroundColor AliceBlue
skinparam classBorderColor Blue
skinparam classFontName Comic Sans 
skinparam classFontSize 20

class Empleado {
 - _id: string
 - nombre_usuario: String
 - nombre: String
 - apellido: String
 - numero_teléfono: String
 - correo: String
 - contraseña: String
}

class PlatosMenu {
  - _id: string
  - categoría: String
  - nombre: String
  - descripción: String
  - variaciones: Array<Variacion>
}

class Variación {
  - variación: String
  - precio: double
}

class Pedido {
 - _id: string
 - numero_pedido: int
 - detalles: Array<DetallePedido>
 - precio_total: double
}

class DetallePedido {
 - tipo: String
 - numero: int
 - nombre: String
 - tamaño: String
 - precio: double
 - cantidad: int
}
PlatosMenu "1" *-- "1..*" Variación : contains
Pedido "1" *-- "1..*" DetallePedido : contains
@enduml